(:*******************************************************:)
(: Test: K-DayTimeDurationDivide-5                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Simple test of dividing a xs:dayTimeDuration with NaN. :)
(:*******************************************************:)
xs:dayTimeDuration("P3DT4H3M3.100S") div xs:double("NaN")