(:*******************************************************:)
(: Test: K2-SeqMAXFunc-5                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-08-04T17:13:26Z                            :)
(: Purpose: Invoke fn:max() with too many arguments.     :)
(:*******************************************************:)
max(("str1", "str2"), "http://www.w3.org/2006/xpath-functions/collation/codepoint", ())