(:*******************************************************:)
(: Test: K-DayTimeDurationSubtract-2                     :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Simple test of substraction PT0S with an xs:dayTimeDuration. :)
(:*******************************************************:)
xs:dayTimeDuration("PT0S") - xs:dayTimeDuration("P3DT4H3M3.100S")
			   eq xs:dayTimeDuration("-P3DT4H3M3.100S")