(:*******************************************************:)
(: Test: K-StringGT-4                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `not('a' ge 'abc')`. :)
(:*******************************************************:)
not('a' ge 'abc')