(:*******************************************************:)
(: Test: K-CeilingFunc-6                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `ceiling("a string")`. :)
(:*******************************************************:)
ceiling("a string")