(:*******************************************************:)
(: Test: K-SeqAVGFunc-39                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `avg((xs:yearMonthDuration("P20Y"), xs:yearMonthDuration("P10M"))) eq xs:yearMonthDuration("P125M")`. :)
(:*******************************************************:)
avg((xs:yearMonthDuration("P20Y"), xs:yearMonthDuration("P10M")))
				      eq xs:yearMonthDuration("P125M")