(:*******************************************************:)
(: Test: K-SeqAVGFunc-35                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `avg((xs:untypedAtomic(3), xs:integer(3), xs:string(1)))`. :)
(:*******************************************************:)
avg((xs:untypedAtomic(3), xs:integer(3), xs:string(1)))