(:*******************************************************:)
(: Test: K-SeqAVGFunc-37                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `avg((xs:float(2), xs:integer(3), "a string", xs:double(2)))`. :)
(:*******************************************************:)
avg((xs:float(2), xs:integer(3), "a string", xs:double(2)))