(:*******************************************************:)
(: Test: K-IRIToURIfunc-2                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `iri-to-uri("http://example.com/", "wrong param")`. :)
(:*******************************************************:)
iri-to-uri("http://example.com/", "wrong param")