(:*******************************************************:)
(: Test: K-SeqExactlyOneFunc-1                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `exactly-one(1, 2)`. :)
(:*******************************************************:)
exactly-one(1, 2)