(:*******************************************************:)
(: Test: K-DaysFromDurationFunc-2                        :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `days-from-duration((), "Wrong param")`. :)
(:*******************************************************:)
days-from-duration((), "Wrong param")