(:*******************************************************:)
(: Test: K-NumericEqual-8                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:decimal(1.1) eq xs:decimal(1.1)`. :)
(:*******************************************************:)
xs:decimal(1.1) eq xs:decimal(1.1)