(:*******************************************************:)
(: Test: K-StringToCodepointFunc-20                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: Combine string-to-codepoints() and a predicate. :)
(:*******************************************************:)
empty(string-to-codepoints("Thérèse")[last() - 7])