(:*******************************************************:)
(: Test: K-HexBinaryEQ-2                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Compare two hexBinary values.                :)
(:*******************************************************:)
xs:hexBinary("FF") ne xs:hexBinary("aa")