(:*******************************************************:)
(: Test: K-ValCompTypeChecking-14                        :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A value comparison involving empty sequence(s). :)
(:*******************************************************:)
empty(1 eq ())