(:*******************************************************:)
(: Test: K-ValCompTypeChecking-31                        :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Compare xs:untypedAtomic and xs:string.      :)
(:*******************************************************:)
"a string" eq xs:untypedAtomic("a string")