(:*******************************************************:)
(: Test: K-SeqUnorderedFunc-2                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `unordered(1, 2)`.  :)
(:*******************************************************:)
unordered(1, 2)