(:*******************************************************:)
(: Test: K-TimeSubtract-5                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: The '+' operator is not available between xs:time and xs:time. :)
(:*******************************************************:)
xs:time("08:01:23") + xs:time("08:01:23")