(:*******************************************************:)
(: Test: K-TimeSubtract-3                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: The '-' operator is not available between xs:yearMonthDuration and xs:time. :)
(:*******************************************************:)
xs:dayTimeDuration("P3D") - xs:time("08:01:23")