(:*******************************************************:)
(: Test: K-SeqExactlyOneFunc-3                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `exactly-one( (1, 2, 3) )`. :)
(:*******************************************************:)
exactly-one( (1, 2, 3) )