(:*******************************************************:)
(: Test: K-SeqRemoveFunc-12                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `remove((3.1, "four"), 1)`. :)
(:*******************************************************:)
remove((3.1, "four"), 1)