(:*******************************************************:)
(: Test: K-SeqRemoveFunc-15                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: Combine fn:remove() with operator 'eq'.      :)
(:*******************************************************:)
5 eq remove((5, 1e0), 2)