(:*******************************************************:)
(: Test: K-FunctionCallExpr-1                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `func-does-not-exist(1, 2, 3)`. :)
(:*******************************************************:)
func-does-not-exist(1, 2, 3)