(:*******************************************************:)
(: Test: K-FunctionCallExpr-18                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: No function by name fn:format-date() exists(although one does in XSL-T). :)
(:*******************************************************:)
format-dateTime(current-date(), "[Y0001]-[M01]-[D01]")