(:*******************************************************:)
(: Test: K-FunctionCallExpr-25                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: No function by name fn:generate-id() exists(although one does in XSL-T). :)
(:*******************************************************:)
generate-id()