(:*******************************************************:)
(: Test: K-NumericGT-16                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `not(xs:float("NaN") ge 1)`. :)
(:*******************************************************:)
not(xs:float("NaN") ge 1)