(:*******************************************************:)
(: Test: K-NodeLocalNameFunc-1                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `local-name((), "wrong param")`. :)
(:*******************************************************:)
local-name((), "wrong param")