(:*******************************************************:)
(: Test: K-SeqMINFunc-36                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `min((xs:untypedAtomic("3"), "a string"))`. :)
(:*******************************************************:)
min((xs:untypedAtomic("3"), "a string"))