(:*******************************************************:)
(: Test: K-InScopePrefixesFunc-2                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `in-scope-prefixes("string", "nodetest", "wrong param")`. :)
(:*******************************************************:)
in-scope-prefixes("string", "nodetest", "wrong param")