(:*******************************************************:)
(: Test: K-SeqDistinctValuesFunc-10                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal(distinct-values((1, 2.0, 3, 2)), (1, 2.0, 3))`. :)
(:*******************************************************:)
deep-equal(distinct-values((1, 2.0, 3, 2)), (1, 2.0, 3))