(:*******************************************************:)
(: Test: K-ContextCurrentDateFunc-2                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: Test that the Dynamic Context property 'current dateTime' when presented as a xs:date is stable during execution. :)
(:*******************************************************:)
current-date() eq current-date()