(:*******************************************************:)
(: Test: K-BooleanEqual-5                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A complex value-comparison involving xs:boolean. :)
(:*******************************************************:)
((((((((((((false() eq false()) eq false()) eq false())
					eq false()) eq false()) eq false()) eq false())
					eq false()) eq false()) eq false()) eq false())
					eq false()) eq false()