(:*******************************************************:)
(: Test: K-SeqBooleanFunc-29                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `boolean('nada')`.  :)
(:*******************************************************:)
boolean('nada')