(:*******************************************************:)
(: Test: K-SeqBooleanFunc-10                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: fn:boolean() invoked on an non-empty xs:untypedAtomic should return true. :)
(:*******************************************************:)
boolean(xs:untypedAtomic("string"))