(:*******************************************************:)
(: Test: K-SeqBooleanFunc-20                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `boolean(1.1e1)`.   :)
(:*******************************************************:)
boolean(1.1e1)