(:*******************************************************:)
(: Test: K-ForExprWithout-16                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `8 eq (for $foo in 1, $foo in 3, $moo in 5 return $moo + $foo)`. :)
(:*******************************************************:)
8 eq (for $foo in 1, $foo in 3, $moo in 5 return $moo + $foo)