(:*******************************************************:)
(: Test: K-ForExprWithout-18                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A for variable binding to the empty sequence. :)
(:*******************************************************:)
empty(for $var in () return current-time())