(:*******************************************************:)
(: Test: K-TraceFunc-5                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `empty(trace((), "trace message"))`. :)
(:*******************************************************:)
empty(trace((), "trace message"))