(:*******************************************************:)
(: Test: K-RangeExpr-26                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `empty(0 to -5)`.   :)
(:*******************************************************:)
empty(0 to -5)