(:*******************************************************:)
(: Test: K-StringLengthFunc-1                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `string-length("a string", "wrong param")`. :)
(:*******************************************************:)
string-length("a string", "wrong param")