(:*******************************************************:)
(: Test: K-LogicExpr-18                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: An 'or' expression whose operands EBV cannot be extracted from. :)
(:*******************************************************:)
current-date() or current-date()