(:*******************************************************:)
(: Test: K-YearMonthDurationMultiply-2                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Simple test of multiplying 3 with xs:yearMonthDuration. :)
(:*******************************************************:)
3 * xs:yearMonthDuration("P3Y36M")
			eq xs:yearMonthDuration("P18Y")