(:*******************************************************:)
(: Test: K-NormalizeSpaceFunc-1                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `normalize-space("a string", "wrong param")`. :)
(:*******************************************************:)
normalize-space("a string", "wrong param")