(:*******************************************************:)
(: Test: K-CondExpr-2                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `if(()) then false() else true()`. :)
(:*******************************************************:)
if(()) then false() else true()