(:*******************************************************:)
(: Test: K-FunctionCallExpr-20                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: No function by name fn:format-date() exists(although one does in XSL-T). :)
(:*******************************************************:)
format-dateTime(current-dateTime(), "[M01]/[D01]/[Y0001] at [H01]:[m01]:[s01]")