(:*******************************************************:)
(: Test: K-FunctionCallExpr-3                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:func-does-not-exist(1, 2, 3)`. :)
(:*******************************************************:)
xs:func-does-not-exist(1, 2, 3)