(:*******************************************************:)
(: Test: K-FunctionCallExpr-22                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: No function by name fn:current() exists(although one does in XSL-T). :)
(:*******************************************************:)
current()