(:*******************************************************:)
(: Test: K-FunctionCallExpr-23                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: No function by name fn:unparsed-entity-uri() exists(although one does in XSL-T). :)
(:*******************************************************:)
unparsed-entity-uri("example.com/file.ext")