(:*******************************************************:)
(: Test: K-GenCompNE-32                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: General comparison which fails due to invalid operator combination or casting. :)
(:*******************************************************:)
3 != xs:untypedAtomic("three")