(:*******************************************************:)
(: Test: K-SeqAVGFunc-32                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `avg(xs:anyURI("a string"))`. :)
(:*******************************************************:)
avg(xs:anyURI("a string"))