(:*******************************************************:)
(: Test: K-SeqAVGFunc-38                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `avg((xs:yearMonthDuration("P20Y"), (3, 4, 5)))`. :)
(:*******************************************************:)
avg((xs:yearMonthDuration("P20Y"), (3, 4, 5)))