(:*******************************************************:)
(: Test: K-TimezoneFromDateFunc-7                        :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(timezone-from-date(xs:date("2004-10-12")))`. :)
(:*******************************************************:)
empty(timezone-from-date(xs:date("2004-10-12")))