(:*******************************************************:)
(: Test: K-CondExpr-9                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: An if-test which EBV cannot be extracted from. :)
(:*******************************************************:)
0 eq (if(xs:anyURI("")) then 1 else 0)