(:*******************************************************:)
(: Test: K-YearMonthDurationMultiply-7                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Simple test of multiplying a xs:yearMonthDuration with NaN. :)
(:*******************************************************:)
xs:yearMonthDuration("P3Y3M") * xs:double("NaN")