(:*******************************************************:)
(: Test: K-CondExpr-5                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: An expression involving the if expression that trigger certain optimization paths in some implementations(#2). :)
(:*******************************************************:)
if((1, 2, 3, hours-from-time(current-time()))[1])
		then true() else false()