(:*******************************************************:)
(: Test: K-SeqSUMFunc-23                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `sum("a string")`.  :)
(:*******************************************************:)
sum("a string")