(:*******************************************************:)
(: Test: K-SeqCountFunc-18                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `not(count((1, 2, current-time(), 4))) eq false()`. :)
(:*******************************************************:)
not(count((1, 2, current-time(), 4))) eq false()