(:*******************************************************:)
(: Test: K-QuantExprWithout-14                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `not(every $foo in 1 satisfies false())`. :)
(:*******************************************************:)
not(every $foo in 1 satisfies false())