(:*******************************************************:)
(: Test: K-DefaultNamespaceProlog-4                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A 'declare default function namespace' expression containing many comments, using quotes for the URILiteral. :)
(:*******************************************************:)
(::)declare(::)default(::)function(::)namespace(::)"http://example.com/"(::);(::)1(::)eq(::)1(::)