(:*******************************************************:)
(: Test: K-SeqMAXFunc-39                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `max(xs:anyURI("example.com/")) eq xs:anyURI("example.com/")`. :)
(:*******************************************************:)
max(xs:anyURI("example.com/")) eq xs:anyURI("example.com/")