(:*******************************************************:)
(: Test: K-ReplaceFunc-9                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A '$' cannot be followed by whitespace.      :)
(:*******************************************************:)
replace("input", "in", "thisIsInvalid$ ")