(:*******************************************************:)
(: Test: K2-SeqMINFunc-6                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-08-04T17:13:26Z                            :)
(: Purpose: Invoke fn:min() with too many arguments.     :)
(:*******************************************************:)
min(("str1", "str2"), "http://www.w3.org/2006/xpath-functions/collation/codepoint", ())