(:*******************************************************:)
(: Test: K-NodeLocalNameFunc-2                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `if(false()) then local-name() else true()`. :)
(:*******************************************************:)
if(false()) then local-name() else true()