(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-52                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal((), reverse(0 to -5))`. :)
(:*******************************************************:)
deep-equal((), reverse(0 to -5))