(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-15                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `not(deep-equal(xs:double("NaN"), xs:double(0)))`. :)
(:*******************************************************:)
not(deep-equal(xs:double("NaN"), xs:double(0)))