(:*******************************************************:)
(: Test: K-SeqSUMFunc-2                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `sum(1, 1, "wrong param")`. :)
(:*******************************************************:)
sum(1,  1, "wrong param")