(:*******************************************************:)
(: Test: K-SeqSUMFunc-24                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `sum(xs:anyURI("a string"))`. :)
(:*******************************************************:)
sum(xs:anyURI("a string"))