(:*******************************************************:)
(: Test: K2-DirectConElemContent-7                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-08-04T17:13:26Z                            :)
(: Purpose: Test that the typed value of comment nodes is correct. :)
(:*******************************************************:)
<!-- a comment --> instance of comment()