(:*******************************************************:)
(: Test: K-SeqIndexOfFunc-18                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal(index-of((1, 2, "three", 5, 5, 6), 5), (4, 5))`. :)
(:*******************************************************:)
deep-equal(index-of((1, 2, "three", 5, 5, 6), 5), (4, 5))