(:*******************************************************:)
(: Test: K-SeqIndexOfFunc-16                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(index-of(xs:anyURI("example.com/"), xs:hexBinary("FF")))`. :)
(:*******************************************************:)
empty(index-of(xs:anyURI("example.com/"), xs:hexBinary("FF")))