(:*******************************************************:)
(: Test: K-SeqIndexOfFunc-21                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal(index-of(("a", "sport", "and", "a", "pastime"), "a"), (1, 4))`. :)
(:*******************************************************:)
deep-equal(index-of(("a", "sport", "and", "a", "pastime"), "a"), (1, 4))