(:*******************************************************:)
(: Test: K-SeqIndexOfFunc-8                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(index-of(xs:float("NaN"), xs:double("NaN")))`. :)
(:*******************************************************:)
empty(index-of(xs:float("NaN"), xs:double("NaN")))