(:*******************************************************:)
(: Test: K-SeqIndexOfFunc-19                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(index-of((10, 20, 30, 40), 35))`. :)
(:*******************************************************:)
empty(index-of((10, 20, 30, 40), 35))