(:*******************************************************:)
(: Test: K-NotFunc-10                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: fn:not() combined with fn:boolean().         :)
(:*******************************************************:)
not(fn:boolean((1, 2, 3, current-time())[1] treat as xs:integer)) eq false()