(:*******************************************************:)
(: Test: K-SeqMAXFunc-42                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `max(("a string", QName("example.com/", "ncname")))`. :)
(:*******************************************************:)
max(("a string", QName("example.com/", "ncname")))