(:*******************************************************:)
(: Test: K-SeqMAXFunc-37                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `max(("a string", xs:untypedAtomic("3")))`. :)
(:*******************************************************:)
max(("a string", xs:untypedAtomic("3")))