(:*******************************************************:)
(: Test: K-SeqExprCastable-30                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `not("three" castable as xs:float)`. :)
(:*******************************************************:)
not("three" castable as xs:float)