(:*******************************************************:)
(: Test: K-SeqExprCastable-32                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `not("three" castable as xs:decimal)`. :)
(:*******************************************************:)
not("three" castable as xs:decimal)