(:*******************************************************:)
(: Test: K-TimeSubtract-8                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: The 'mod' operator is not available between xs:time and xs:time. :)
(:*******************************************************:)
xs:time("08:01:23") mod xs:time("08:01:23")