(:*******************************************************:)
(: Test: K-SeqDistinctValuesFunc-11                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `exists(distinct-values((1, 2, 3, 1)))`. :)
(:*******************************************************:)
exists(distinct-values((1, 2, 3, 1)))