(:*******************************************************:)
(: Test: K-SeqMINFunc-51                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `min((xs:float(0.0E0), xs:float(-0.0E0))) eq xs:float("-0")`. :)
(:*******************************************************:)
min((xs:float(0.0E0), xs:float(-0.0E0))) eq xs:float("-0")