(:*******************************************************:)
(: Test: K-BooleanLT-2                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Compare two xs:boolean values.               :)
(:*******************************************************:)
false() le true()