(:*******************************************************:)
(: Test: K-DurationEQ-29                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Test comparing xs:duration and xs:yearMonthDuration stressing value representations are normalized properly. :)
(:*******************************************************:)
xs:yearMonthDuration("P1M") ne xs:duration("P31D")