(:*******************************************************:)
(: Test: K-gMonthEQ-1                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Simple test of 'eq' for xs:gMonth, returning positive. :)
(:*******************************************************:)
xs:gMonth("--11  ") eq xs:gMonth("--11")