(:*******************************************************:)
(: Test: K-NumericGT-7                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:double(1) gt xs:double(-1)`. :)
(:*******************************************************:)
xs:double(1) gt xs:double(-1)