(:*******************************************************:)
(: Test: K-SeqExprCast-230                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Testing timezone field in xs:gYear: the minute component cannot be -60. :)
(:*******************************************************:)
xs:gYear("1956-10:60")