(:*******************************************************:)
(: Test: K-SeqExprCast-228                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Testing timezone field in xs:gYear: the hour component cannot be +15. :)
(:*******************************************************:)
xs:gYear("1956+15:00")