(:*******************************************************:)
(: Test: K-SeqExprCast-17                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `'0' cast as xs:boolean eq false()`. :)
(:*******************************************************:)
'0' cast as xs:boolean eq false()