(:*******************************************************:)
(: Test: K-SeqExprCast-226                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `xs:gYear("1111 Z")`. :)
(:*******************************************************:)
xs:gYear("1111 Z")