(:*******************************************************:)
(: Test: K-SeqExprCast-299                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: The xs:gMonthDay value '--02-30' represents a non-existent date. :)
(:*******************************************************:)
xs:gMonthDay("--02-30")