(:*******************************************************:)
(: Test: K-SeqExprCast-216                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `xs:gYear("12")`.   :)
(:*******************************************************:)
xs:gYear("12")