(:*******************************************************:)
(: Test: K-SeqExprCast-751                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: It is not possible to extract an Effective Boolean Value from the type xs:dayTimeDuration, with the boolean() function. :)
(:*******************************************************:)
boolean(xs:dayTimeDuration("P3DT2H"))