(:*******************************************************:)
(: Test: K-SeqExprCast-359                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: '-21:01:50' is an invalid lexical representation for xs:time. :)
(:*******************************************************:)
xs:time("-21:01:50")