(:*******************************************************:)
(: Test: K-SeqExprCast-261                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: '--13' is an invalid lexical representation for xs:gMonth. :)
(:*******************************************************:)
xs:gMonth("--13")