(:*******************************************************:)
(: Test: K-SeqExprCast-14                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `'1' cast as xs:boolean eq true()`. :)
(:*******************************************************:)
'1' cast as xs:boolean eq true()