(:*******************************************************:)
(: Test: K-SeqExprCast-293                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: '--00-01' is an invalid lexical representation for xs:gMonthDay. :)
(:*******************************************************:)
xs:gMonthDay("--00-01")