(:*******************************************************:)
(: Test: K-SeqExprCast-959                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: It is not possible to extract an Effective Boolean Value from the type xs:gYearMonth, with the boolean() function. :)
(:*******************************************************:)
boolean(xs:gYearMonth("1999-11"))