(:*******************************************************:)
(: Test: K-SeqExprCast-198                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: At least one number and its designator must be present in a xs:yearMonthDuration value. :)
(:*******************************************************:)
xs:yearMonthDuration("P")