(:*******************************************************:)
(: Test: K-MatchesFunc-5                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: The flags argument cannot contain whitespace. :)
(:*******************************************************:)
matches("input", "pattern", " ")