(:*******************************************************:)
(: Test: K-MatchesFunc-3                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: The third argument cannot be the empty sequence. :)
(:*******************************************************:)
matches("input", "pattern", ())