(:*******************************************************:)
(: Test: K2-AnyURIEqual-2                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-08-04T17:13:26Z                            :)
(: Purpose: Invoked 'lt' on xs:anyURI values.            :)
(:*******************************************************:)
not(xs:anyURI("http://example.com/B") lt xs:anyURI("http://example.com/A"))