(:*******************************************************:)
(: Test: K-StringJoinFunc-2                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `string-join("a string", "a string", "wrong param")`. :)
(:*******************************************************:)
string-join("a string", "a string", "wrong param")