(:*******************************************************:)
(: Test: K-FilterExpr-30                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `empty((1, 2, 3)[false()])`. :)
(:*******************************************************:)
empty((1, 2, 3)[false()])