(:*******************************************************:)
(: Test: K-FilterExpr-77                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `empty(()[last()])`. :)
(:*******************************************************:)
empty(()[last()])