(:*******************************************************:)
(: Test: K-FilterExpr-37                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: One xs:anyURI value is a valid predicate.    :)
(:*******************************************************:)
deep-equal((1, 2, 3), (1, 2, 3)[xs:anyURI("example.com/")])