(:*******************************************************:)
(: Test: K-FilterExpr-70                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal((1, 2), (0, 1, 2)[if(. eq 1) then 2 else 3])`. :)
(:*******************************************************:)
deep-equal((1, 2), (0, 1, 2)[if(. eq 1) then 2 else 3])