(:*******************************************************:)
(: Test: K-FilterExpr-86                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A predicate that never can match.            :)
(:*******************************************************:)
empty(current-time()[2])