(:*******************************************************:)
(: Test: K-CodepointToStringFunc-26                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `codepoints-to-string(1114112)`. :)
(:*******************************************************:)
codepoints-to-string(1114112)