(:*******************************************************:)
(: Test: K-CodepointToStringFunc-8                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `codepoints-to-string(8)`. :)
(:*******************************************************:)
codepoints-to-string(8)