(:*******************************************************:)
(: Test: K-NumericEqual-13                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:double(-1.1) eq xs:double(-1.1)`. :)
(:*******************************************************:)
xs:double(-1.1) eq xs:double(-1.1)