(:*******************************************************:)
(: Test: K-NumericEqual-22                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:double("INF") ne xs:double("-INF")`. :)
(:*******************************************************:)
xs:double("INF") ne xs:double("-INF")