(:*******************************************************:)
(: Test: K-NumericEqual-20                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:double("INF") eq xs:double("INF")`. :)
(:*******************************************************:)
xs:double("INF") eq xs:double("INF")