(:*******************************************************:)
(: Test: K-NumericEqual-29                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:float(1.1) ne xs:float(2.1)`. :)
(:*******************************************************:)
xs:float(1.1) ne xs:float(2.1)