(:*******************************************************:)
(: Test: K-NumericEqual-34                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:float("INF") eq xs:float("INF")`. :)
(:*******************************************************:)
xs:float("INF") eq xs:float("INF")