(:*******************************************************:)
(: Test: K-SeqSubsequenceFunc-21                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(subsequence((1, 2), 4))`. :)
(:*******************************************************:)
empty(subsequence((1, 2), 4))