(:*******************************************************:)
(: Test: K-SeqSubsequenceFunc-35                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(subsequence((current-time(), 1), 4))`. :)
(:*******************************************************:)
empty(subsequence((current-time(), 1), 4))