(:*******************************************************:)
(: Test: K-ContextCurrentTimeFunc-1                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `current-time("WRONG PARAM")`. :)
(:*******************************************************:)
current-time("WRONG PARAM")