(:*******************************************************:)
(: Test: K-AdjTimeToTimezoneFunc-1                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `adjust-time-to-timezone()`. :)
(:*******************************************************:)
adjust-time-to-timezone()