(:*******************************************************:)
(: Test: K-SeqExistsFunc-1                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `exists(1, 2)`.     :)
(:*******************************************************:)
exists(1, 2)