(:*******************************************************:)
(: Test: K-StartsWithFunc-6                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `starts-with("foo", "foo")`. :)
(:*******************************************************:)
starts-with("foo", "foo")