(:*******************************************************:)
(: Test: K-SeqBooleanFunc-27                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `not(empty((1, 2)))`. :)
(:*******************************************************:)
not(empty((1, 2)))