(:*******************************************************:)
(: Test: K-SeqBooleanFunc-16                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `true() eq boolean(remove((xs:hexBinary("FF"), 1), 1) treat as xs:integer)`. :)
(:*******************************************************:)
true() eq boolean(remove((xs:hexBinary("FF"), 1), 1) treat as xs:integer)