(:*******************************************************:)
(: Test: K-GenCompEq-27                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: General comparison involving xs:untypedAtomic/xs:string. :)
(:*******************************************************:)
not(xs:untypedAtomic("a string") = "a stringDIFF")