(:*******************************************************:)
(: Test: K-GenCompEq-59                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: General comparison which fails due to invalid operator combination or casting. :)
(:*******************************************************:)
false() = xs:anyURI("example.com/")