(:*******************************************************:)
(: Test: K-GenCompEq-7                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Example from the XPath 2.0 specification.    :)
(:*******************************************************:)
(2, 3) = (3, 4)