(:*******************************************************:)
(: Test: K-GenCompEq-31                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: General comparison with remove() as operand, resulting in incompatible operand types. :)
(:*******************************************************:)
6 = remove(("a string", 6), 2)