(:*******************************************************:)
(: Test: K-GenCompEq-8                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Example from the XPath 2.0 specification.    :)
(:*******************************************************:)
not((1, 2) = (3, 4))