(:*******************************************************:)
(: Test: K-YearMonthDurationAdd-1                        :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Simple test of adding an xs:yearMonthDuration with P0M. :)
(:*******************************************************:)
xs:yearMonthDuration("P3Y3M") + xs:yearMonthDuration("P0M")
			   eq xs:yearMonthDuration("P3Y3M")