(:*******************************************************:)
(: Test: K-NumericIntegerDivide-37                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `1 idiv xs:double("NaN")`. :)
(:*******************************************************:)
1 idiv xs:double("NaN")