(:*******************************************************:)
(: Test: K-NumericIntegerDivide-33                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:float("INF") idiv xs:float(3)`. :)
(:*******************************************************:)
xs:float("INF") idiv xs:float(3)