(:*******************************************************:)
(: Test: K-StartsWithFunc-11                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `not(starts-with("", "a string"))`. :)
(:*******************************************************:)
not(starts-with("", "a string"))