(:*******************************************************:)
(: Test: K-SeqSubsequenceFunc-26                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `subsequence((1, 2, 3.1, "four"), 1, 1)`. :)
(:*******************************************************:)
subsequence((1, 2, 3.1, "four"), 1, 1)