(:*******************************************************:)
(: Test: K-SeqSubsequenceFunc-28                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `1 eq subsequence(("1", 2, 3.1, "four"), 1, 1)`. :)
(:*******************************************************:)
1 eq subsequence(("1", 2, 3.1, "four"), 1, 1)