(:*******************************************************:)
(: Test: K-NumericAdd-39                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Arithmethics involving operands of integer type but with wrong cardinality. :)
(:*******************************************************:)
1 + (1, 2)