(:*******************************************************:)
(: Test: K-ValCompTypeChecking-19                        :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Value comparison involving xs:untypedAtomic, which leads to an inexistent operator mapping. :)
(:*******************************************************:)
xs:double(1) ne xs:untypedAtomic("0")