(:*******************************************************:)
(: Test: K-ContextLastFunc-1                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `last(1)`.          :)
(:*******************************************************:)
last(1)