(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-50                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `not(deep-equal((), (1, 1, 1)))`. :)
(:*******************************************************:)
not(deep-equal((), (1, 1, 1)))