(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-34                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal(index-of((20, 20), 20), (1, 2))`. :)
(:*******************************************************:)
deep-equal(index-of((20, 20), 20), (1, 2))