(:*******************************************************:)
(: Test: K-ContextImplicitTimezoneFunc-3                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: Test that implicit-timezone() do return a value. :)
(:*******************************************************:)
exists(seconds-from-duration(implicit-timezone()))