(:*******************************************************:)
(: Test: K-SeqReverseFunc-19                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: Apply a predicate to the result of fn:reverse(). :)
(:*******************************************************:)
deep-equal((3, 2, 1), reverse((1, 2, 3))[true()])