(:*******************************************************:)
(: Test: K-LogicExpr-34                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Non-empty xs:anyURIs have an EBV value of true. :)
(:*******************************************************:)
xs:anyURI("example.com/") and xs:anyURI("example.com/")