(:*******************************************************:)
(: Test: K-LogicExpr-19                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: An 'and' expression having an operand which EBV cannot be extracted from. :)
(:*******************************************************:)
current-date() and current-date()