(:*******************************************************:)
(: Test: K-LogicExpr-36                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Empty xs:anyURIs have an EBV value of false. :)
(:*******************************************************:)
not(xs:anyURI("") and xs:anyURI("example.com/"))