(:*******************************************************:)
(: Test: K-LogicExpr-33                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `not(false() and (1, current-time())[1] treat as xs:integer)`. :)
(:*******************************************************:)
not(false() and (1, current-time())[1] treat as xs:integer)