(:*******************************************************:)
(: Test: K-LogicExpr-32                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `not((1, current-time())[1] treat as xs:integer and false())`. :)
(:*******************************************************:)
not((1, current-time())[1] treat as xs:integer and false())