(:*******************************************************:)
(: Test: K-LogicExpr-15                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `(0, current-time())[1] treat as xs:integer or true()`. :)
(:*******************************************************:)
(0, current-time())[1] treat as xs:integer or true()