(:*******************************************************:)
(: Test: K-SeqIndexOfFunc-13                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(index-of((), 4))`. :)
(:*******************************************************:)
empty(index-of((), 4))