(:*******************************************************:)
(: Test: K-DurationEQ-6                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: The xs:duration values P365D and P1Y are not equal. :)
(:*******************************************************:)
xs:duration("P1Y") ne xs:duration("P365D")