(:*******************************************************:)
(: Test: K-DateTimeFunc-1                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: Passing too few parameters(none) to fn:dateTime(). :)
(:*******************************************************:)
dateTime()