(:*******************************************************:)
(: Test: K-SeqExprTreat-10                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: Exactly-one xs:integer does not match empty-sequence(). :)
(:*******************************************************:)
1 treat as empty-sequence()