(:*******************************************************:)
(: Test: K-ResolveURIFunc-5                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(resolve-uri((), "http://www.example.com/"))`. :)
(:*******************************************************:)
empty(resolve-uri((), "http://www.example.com/"))