(:*******************************************************:)
(: Test: K-XQueryComment-15                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A comment inside a comment that isn't terminated. :)
(:*******************************************************:)
1(: content (: this comment does not end :)