(:*******************************************************:)
(: Test: K-SeqInsertBeforeFunc-2                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `insert-before("wrong params", 2)`. :)
(:*******************************************************:)
insert-before("wrong params", 2)