(:*******************************************************:)
(: Test: K-PrefixFromQName-3                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(prefix-from-QName( () ))`. :)
(:*******************************************************:)
empty(prefix-from-QName( () ))