(:*******************************************************:)
(: Test: K-PrefixFromQName-2                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `prefix-from-QName(1, 2)`. :)
(:*******************************************************:)
prefix-from-QName(1, 2)