(:*******************************************************:)
(: Test: K-NormalizeUnicodeFunc-2                        :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `normalize-unicode("a string", "NFC", "wrong param")`. :)
(:*******************************************************:)
normalize-unicode("a string", "NFC", "wrong param")