/* Generated By:JJTree: Do not edit this line. ASTChoiceExpression.java */

package org.eclipse.jst.jsp.core.internal.java.jspel;

public class ASTChoiceExpression extends SimpleNode {
  public ASTChoiceExpression(int id) {
    super(id);
  }

  public ASTChoiceExpression(JSPELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSPELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
