/* Generated By:JJTree: Do not edit this line. ASTLiteral.java */

package org.eclipse.jst.jsp.core.internal.java.jspel;

public class ASTLiteral extends SimpleNode {
  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(JSPELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSPELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
