/* Generated By:JJTree: Do not edit this line. ASTValue.java */

package org.eclipse.jst.jsp.core.internal.java.jspel;

public class ASTValue extends SimpleNode {
  public ASTValue(int id) {
    super(id);
  }

  public ASTValue(JSPELParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JSPELParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
