(:*******************************************************:)
(: Test: K-NumericGT-4                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:decimal(1) ge xs:decimal(1)`. :)
(:*******************************************************:)
xs:decimal(1) ge xs:decimal(1)