(:*******************************************************:)
(: Test: K-NumericGT-5                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `0 gt xs:double("-INF")`. :)
(:*******************************************************:)
0 gt xs:double("-INF")