(:*******************************************************:)
(: Test: K-SeqExprCast-173                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: At least one number and its designator must be present in a xs:dayTimeDuration value. :)
(:*******************************************************:)
xs:dayTimeDuration("P")