(:*******************************************************:)
(: Test: K-SeqExprCast-98                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `exists(xs:hexBinary("Ab08bcFFAA08b6"))`. :)
(:*******************************************************:)
exists(xs:hexBinary("Ab08bcFFAA08b6"))