(:*******************************************************:)
(: Test: K-SeqExprCast-440                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: 'castable as' involving xs:string as sourceType and xs:NOTATION should fail due to it involving xs:NOTATION. :)
(:*******************************************************:)
not(xs:string("an arbitrary string") castable as xs:NOTATION)