(:*******************************************************:)
(: Test: K-SeqExprCast-65                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Casting to xs:notation is not allowed.       :)
(:*******************************************************:)
xs:NOTATION(xs:anyURI('example.com/'))