(:*******************************************************:)
(: Test: K-SeqExprCast-953                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: The xs:gYearMonth constructor function must be passed exactly one argument, not zero. :)
(:*******************************************************:)
xs:gYearMonth()