(:*******************************************************:)
(: Test: K-SeqExprCast-175                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A 'T' separator in a xs:dayTimeDuration must be followed by time components. :)
(:*******************************************************:)
xs:dayTimeDuration("P1DT")