(:*******************************************************:)
(: Test: K-SeqExprCast-148                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A preceding plus sign('+') is disallowed for xs:duration. :)
(:*******************************************************:)
xs:duration("+P1Y2M123DT10H30M99S")