(:*******************************************************:)
(: Test: K-SeqExprCast-223                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `xs:gYear("a1111")`. :)
(:*******************************************************:)
xs:gYear("a1111")