(:*******************************************************:)
(: Test: K-SeqExprCast-699                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: It is not possible to extract an Effective Boolean Value from the type xs:yearMonthDuration, with the boolean() function. :)
(:*******************************************************:)
boolean(xs:yearMonthDuration("P1Y12M"))