(:*******************************************************:)
(: Test: K-SeqExprCast-95                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `xs:hexBinary("0xFF")`. :)
(:*******************************************************:)
xs:hexBinary("0xFF")