(:*******************************************************:)
(: Test: K-SeqExprCast-385                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: A valid xs:dateTime is an invalid xs:date.   :)
(:*******************************************************:)
xs:date("2002-02-15T08:12:12")