(:*******************************************************:)
(: Test: K-SeqExprCast-254                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Testing timezone field in xs:gDay: the minute field must always be present. :)
(:*******************************************************:)
xs:gDay("---08-10")