(:*******************************************************:)
(: Test: K-SeqExprCast-197                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A preceding 'P' must always exist in a xs:yearMonthDuration value. :)
(:*******************************************************:)
xs:yearMonthDuration("20Y15M")