(:*******************************************************:)
(: Test: K-SeqExprCast-178                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: 'P24M1D' is an invalid lexical representation for xs:dayTimeDuration. :)
(:*******************************************************:)
xs:dayTimeDuration("P24M1D")