(:*******************************************************:)
(: Test: K-SeqExprCast-222                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `xs:gYear("1111a")`. :)
(:*******************************************************:)
xs:gYear("1111a")