(:*******************************************************:)
(: Test: K-SeqExprCast-298                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: Testing timezone field in xs:gMonthDay: the minute field must always be present. :)
(:*******************************************************:)
xs:gMonthDay("--11-08-10")