(:*******************************************************:)
(: Test: K-gMonthEQ-2                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Simple test of 'eq' for xs:gMonth.           :)
(:*******************************************************:)
not(xs:gMonth("--11") eq xs:gMonth("--01"))