(:*******************************************************:)
(: Test: K2-SeqIDREFFunc-1                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-08-04T17:13:26Z                            :)
(: Purpose: A test whose essence is: `idref((), ())`.    :)
(:*******************************************************:)
idref((), ())