(:*******************************************************:)
(: Test: K-SeqExprCast-150                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A preceding 'P' must always exist in a xs:duration value. :)
(:*******************************************************:)
xs:duration("1Y2M123DT10H30M99S")