(:*******************************************************:)
(: Test: K-SeqExprCast-262                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: '--431' is an invalid lexical representation for xs:gMonth. :)
(:*******************************************************:)
xs:gMonth("--431")