(:*******************************************************:)
(: Test: K-SeqExprCast-240                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: 'E---01' is an invalid lexical representation for xs:gDay. :)
(:*******************************************************:)
xs:gDay("E---01")