(:*******************************************************:)
(: Test: K-SeqExprCast-269                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Testing timezone field in xs:gMonth: the minute field must always be present. :)
(:*******************************************************:)
xs:gMonth("--08-10")