(:*******************************************************:)
(: Test: K-SeqExprCast-796                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: 'castable as' involving xs:dayTimeDuration as sourceType and xs:NOTATION should fail due to it involving xs:NOTATION. :)
(:*******************************************************:)
not(xs:dayTimeDuration("P3DT2H") castable as xs:NOTATION)