(:*******************************************************:)
(: Test: K-SeqExprCast-241                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: '---01E' is an invalid lexical representation for xs:gDay. :)
(:*******************************************************:)
xs:gDay("---01E")