(:*******************************************************:)
(: Test: K-SeqExprCast-179                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: 'PDT3H2M10.001S' is an invalid lexical representation for xs:dayTimeDuration. :)
(:*******************************************************:)
xs:dayTimeDuration("PDT3H2M10.001S")