(:*******************************************************:)
(: Test: K-SeqExprCast-154                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: 'P24H' is an invalid lexical representation for xs:duration. :)
(:*******************************************************:)
xs:duration("P24H")