(:*******************************************************:)
(: Test: K-SeqExprCast-202                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: '-P3' is an invalid lexical representation for xs:yearMonthDuration. :)
(:*******************************************************:)
xs:yearMonthDuration("-P3")