(:*******************************************************:)
(: Test: K-SeqExprCast-377                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: '+2004-08-01' is an invalid lexical representation, a preceding '+' sign is not allowed for xs:date. :)
(:*******************************************************:)
xs:date("+2004-08-01")