(:*******************************************************:)
(: Test: K-SeqExprCast-300                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: The xs:gMonthDay value '--04-31' represents a non-existent date. :)
(:*******************************************************:)
xs:gMonthDay("--04-31")