(:*******************************************************:)
(: Test: K-SeqExprCast-247                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: '+--08' is an invalid lexical representation for xs:gDay. :)
(:*******************************************************:)
xs:gDay("+--08")