(:*******************************************************:)
(: Test: K-SeqExprCast-900                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: 'castable as' involving xs:time as sourceType and xs:NOTATION should fail due to it involving xs:NOTATION. :)
(:*******************************************************:)
not(xs:time("03:20:00-05:00") castable as xs:NOTATION)