(:*******************************************************:)
(: Test: K-SeqExprCast-252                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Testing timezone field in xs:gDay: the minute component cannot be +60. :)
(:*******************************************************:)
xs:gDay("---08+10:60")