(:*******************************************************:)
(: Test: K-SeqExprCast-382                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:38+02:00                       :)
(: Purpose: '2002-002-15' is an invalid lexical representation for xs:date. :)
(:*******************************************************:)
xs:date("2002-002-15")