(:*******************************************************:)
(: Test: K-SeqExprCast-280                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Testing timezone field in xs:gYearMonth: the minute field must always be present. :)
(:*******************************************************:)
xs:gYearMonth("1999-08-10")