(:*******************************************************:)
(: Test: K-gYearMonthEQ-1                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Simple test of 'eq' for xs:gYearMonth, returning positive. :)
(:*******************************************************:)
xs:gYearMonth("2001-01  ") eq xs:gYearMonth("2001-01")