(:*******************************************************:)
(: Test: K-ReplaceFunc-5                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: Only four arguments are accepted.            :)
(:*******************************************************:)
replace("input", "pattern", "replacement", "", ())