(:*******************************************************:)
(: Test: K-SeqAVGFunc-2                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `avg(1, "wrong param")`. :)
(:*******************************************************:)
avg(1, "wrong param")