(:*******************************************************:)
(: Test: K-SeqAVGFunc-33                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `avg((1, 2, 3, xs:anyURI("a string"), xs:double("NaN")))`. :)
(:*******************************************************:)
avg((1, 2, 3, xs:anyURI("a string"), xs:double("NaN")))