(:*******************************************************:)
(: Test: K-compareFunc-7                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `not(codepoint-equal("cow", "a string"))`. :)
(:*******************************************************:)
not(codepoint-equal("cow", "a string"))