(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-38                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `not( (1, 2, 3) instance of empty-sequence())`. :)
(:*******************************************************:)
not( (1, 2, 3) instance of empty-sequence())