(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-18                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `not((1, 2, 3, 4, 5) instance of xs:integer)`. :)
(:*******************************************************:)
not((1, 2, 3, 4, 5) instance of xs:integer)