(:*******************************************************:)
(: Test: K-FunctionCallExpr-10                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A function call containing an invalid QName as name. :)
(:*******************************************************:)
p:f:lname()