(:*******************************************************:)
(: Test: K-FunctionCallExpr-11                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: No function by name fn:document() exists(although one does in XSL-T). :)
(:*******************************************************:)
document("example.com/file.ext")