(:*******************************************************:)
(: Test: K-FunctionCallExpr-24                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: No function by name fn:unparsed-entity-public-id() exists(although one does in XSL-T). :)
(:*******************************************************:)
unparsed-entity-public-id("entity")