(:*******************************************************:)
(: Test: K-FunctionCallExpr-27                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: No function by name fn:escape-uri() exists(although one did in older 'Functions & Operators' drafts). :)
(:*******************************************************:)
fn:escape-uri("http:/example.com/")