(:*******************************************************:)
(: Test: K-FunctionCallExpr-13                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: No function by name fn:unparsed-text() exists(although one does in XSL-T). :)
(:*******************************************************:)
unparsed-text-available("example.com/file.ext")