(:*******************************************************:)
(: Test: K-StaticBaseURIFunc-3                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `if(static-base-uri()) then true() else true()`. :)
(:*******************************************************:)
if(static-base-uri()) then true() else true()