(:*******************************************************:)
(: Test: K-QuantExprWithout-12                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `every $foo in 1 satisfies true()`. :)
(:*******************************************************:)
every $foo in 1 satisfies true()