(:*******************************************************:)
(: Test: K-QuantExprWithout-5                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A some-quantification applied on fn:count(). :)
(:*******************************************************:)
some $i in (0, 2, 3) satisfies count($i)