(:*******************************************************:)
(: Test: K-QuantExprWithout-41                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `not(some $var in (false(), false(), false()) satisfies $var)`. :)
(:*******************************************************:)
not(some $var in (false(), false(), false()) satisfies $var)