(:*******************************************************:)
(: Test: K-NodeSame-1                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `empty(1 is ())`.   :)
(:*******************************************************:)
empty(1 is ())