(:*******************************************************:)
(: Test: K-DayTimeDurationMultiply-4                     :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Simple test of multiplying 0 with xs:dayTimeDuration. :)
(:*******************************************************:)
0 * xs:dayTimeDuration("P3DT4H3M3.100S")
	                eq xs:dayTimeDuration("PT0S")