(:*******************************************************:)
(: Test: K-TimezoneFromTimeFunc-7                        :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `empty(timezone-from-time(xs:time("23:43:12.765")))`. :)
(:*******************************************************:)
empty(timezone-from-time(xs:time("23:43:12.765")))