(:*******************************************************:)
(: Test: K-ReplaceFunc-1                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: The flags argument cannot contain whitespace. :)
(:*******************************************************:)
replace("input", "pattern", "replacement", " ")