(:*******************************************************:)
(: Test: K-NumericAdd-44                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Invoke the '+' operator with invalid operands. :)
(:*******************************************************:)
"3" + xs:untypedAtomic("3")