(:*******************************************************:)
(: Test: K-NumericAdd-31                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Invoke operator '+' where one of the operands is of type none. :)
(:*******************************************************:)
3 + error()