(:*******************************************************:)
(: Test: K-SeqInsertBeforeFunc-4                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: The second argument to fn:insert-before cannot be the empty sequence. :)
(:*******************************************************:)
insert-before((), (), "a string")