(:*******************************************************:)
(: Test: K-StringToCodepointFunc-10                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal(string-to-codepoints("eee"), (101, 101, 101))`. :)
(:*******************************************************:)
deep-equal(string-to-codepoints("eee"), (101, 101, 101))