(:*******************************************************:)
(: Test: K-SeqExprCastable-34                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `not((1, 2, 3) castable as xs:integer)`. :)
(:*******************************************************:)
not((1, 2, 3) castable as xs:integer)