(:*******************************************************:)
(: Test: K-SeqExprCastable-24                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `not('string' castable as xs:boolean)`. :)
(:*******************************************************:)
not('string' castable as xs:boolean)