(:*******************************************************:)
(: Test: K-SeqExprCastable-29                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `not(xs:anyURI("example.com/") castable as xs:integer)`. :)
(:*******************************************************:)
not(xs:anyURI("example.com/") castable as xs:integer)