(:*******************************************************:)
(: Test: K-SeqExprCastable-35                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `not(() castable as xs:integer)`. :)
(:*******************************************************:)
not(() castable as xs:integer)