(:*******************************************************:)
(: Test: K-SeqExprCastable-14                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: An invalid type for 'castable as' is specified, leading to a syntax error. :)
(:*******************************************************:)
'string' castable as node()