(:*******************************************************:)
(: Test: K-SeqExprCastable-23                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `not(("one", "two") castable as xs:string?)`. :)
(:*******************************************************:)
not(("one", "two") castable as xs:string?)