(:*******************************************************:)
(: Test: K-ValCompTypeChecking-36                        :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Combine error() with a value comparison, testing handling of the 'none' type. :)
(:*******************************************************:)
error() eq error()