(:*******************************************************:)
(: Test: K-ValCompTypeChecking-8                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A value comparison where the cardinality of the operand(s) is wrong. :)
(:*******************************************************:)
3 le (1, 2, 3)