(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-14                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `not(deep-equal(xs:double(0), xs:double("NaN")))`. :)
(:*******************************************************:)
not(deep-equal(xs:double(0), xs:double("NaN")))