(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-31                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `not(deep-equal((1, 1, 1), (1, 1, 3)))`. :)
(:*******************************************************:)
not(deep-equal((1, 1, 1), (1, 1, 3)))