(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-33                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal(index-of((20, 40), 20), (1))`. :)
(:*******************************************************:)
deep-equal(index-of((20, 40), 20), (1))