(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-23                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `not(deep-equal((1, 2, 3), (xs:base64Binary("FFFF"), 2, 3)))`. :)
(:*******************************************************:)
not(deep-equal((1, 2, 3), (xs:base64Binary("FFFF"), 2, 3)))