(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-8                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal(xs:float("NaN"), xs:float("NaN"))`. :)
(:*******************************************************:)
deep-equal(xs:float("NaN"), xs:float("NaN"))