(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-55                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal(0 to -5, ())`. :)
(:*******************************************************:)
deep-equal(0 to -5, ())