(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-13                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `not(deep-equal(xs:float(0), xs:float("NaN")))`. :)
(:*******************************************************:)
not(deep-equal(xs:float(0), xs:float("NaN")))