(:*******************************************************:)
(: Test: K-SeqDeepEqualFunc-9                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal(xs:double("NaN"), xs:double("NaN"))`. :)
(:*******************************************************:)
deep-equal(xs:double("NaN"), xs:double("NaN"))