(:*******************************************************:)
(: Test: K-gYearMonthEQ-3                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Simple test of 'ne' for xs:gYearMonth.       :)
(:*******************************************************:)
xs:gYearMonth("2001-12") ne xs:gYearMonth("2001-11")