(:*******************************************************:)
(: Test: K-gYearMonthEQ-5                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Test that zone offset -00:00 is equal to Z, in xs:gYearMonth. :)
(:*******************************************************:)
xs:gYearMonth("1999-01-00:00") eq xs:gYearMonth("1999-01Z")