(:*******************************************************:)
(: Test: K-DayFromDateTimeFunc-1                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `day-from-dateTime()`. :)
(:*******************************************************:)
day-from-dateTime()