(:*******************************************************:)
(: Test: K-LogicExpr-37                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Non-empty xs:untypedAtomics have an EBV value of true. :)
(:*******************************************************:)
xs:untypedAtomic("a string") and xs:untypedAtomic("a string")