(:*******************************************************:)
(: Test: K-LogicExpr-45                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `"a string is ok" and QName("", "local")`. :)
(:*******************************************************:)
"a string is ok" and QName("", "local")