(:*******************************************************:)
(: Test: K-LogicExpr-17                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: An 'or' expression having an operand which EBV cannot be extracted from. :)
(:*******************************************************:)
0 or current-date()