(:*******************************************************:)
(: Test: K-SeqReverseFunc-2                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `reverse(1, 2)`.    :)
(:*******************************************************:)
reverse(1, 2)