(:*******************************************************:)
(: Test: K-SeqReverseFunc-9                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `exists(reverse((1, 2, 3)))`. :)
(:*******************************************************:)
exists(reverse((1, 2, 3)))