(:*******************************************************:)
(: Test: K-SeqReverseFunc-12                             :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal((3, 2, 1), reverse(1 to 3))`. :)
(:*******************************************************:)
deep-equal((3, 2, 1), reverse(1 to 3))