(:*******************************************************:)
(: Test: K-NumericIntegerDivide-36                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:float("3") idiv xs:float("-INF") eq xs:float(0)`. :)
(:*******************************************************:)
xs:float("3") idiv xs:float("-INF") eq xs:float(0)