(:*******************************************************:)
(: Test: K-NumericIntegerDivide-41                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:double("3") idiv xs:double("INF") eq xs:double(0)`. :)
(:*******************************************************:)
xs:double("3") idiv xs:double("INF") eq xs:double(0)