(:*******************************************************:)
(: Test: K-ExpandedQNameConstructFunc-3                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `QName("http://www.example.com/", "ncname", "error")`. :)
(:*******************************************************:)
QName("http://www.example.com/", "ncname", "error")