(:*******************************************************:)
(: Test: K-ExpandedQNameConstructFunc-5                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A QName cannot start with a digit.           :)
(:*******************************************************:)
QName("http://www.example.com/", "1asd:error")