(:*******************************************************:)
(: Test: K-NumericAdd-42                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Number addition with error() as the right operand. :)
(:*******************************************************:)
3 + error()