(:*******************************************************:)
(: Test: K-NumericAdd-58                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Implementations supporting the static typing feature may raise XPTy0004. :)
(:*******************************************************:)
2 eq (xs:untypedAtomic("1") + remove((1, "two"), 2))