(:*******************************************************:)
(: Test: K-gYearEQ-3                                     :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Simple test of 'ne' for xs:gYear.            :)
(:*******************************************************:)
xs:gYear("1956") ne xs:gYear("1958")