(:*******************************************************:)
(: Test: K-NumericIntegerDivide-47                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: Invoke the 'idiv' operator with invalid operands. :)
(:*******************************************************:)
"3" idiv xs:float(3)