(:*******************************************************:)
(: Test: K-gDayEQ-4                                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Simple test of 'ne' for xs:gDay.             :)
(:*******************************************************:)
not(xs:gDay("---01") ne xs:gDay("---01"))