(:*******************************************************:)
(: Test: K-gDayEQ-2                                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Simple test of 'eq' for xs:gDay.             :)
(:*******************************************************:)
not(xs:gDay("---31") eq xs:gDay("---01"))