(:*******************************************************:)
(: Test: K2-DirectConElemContent-2                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-08-04T17:13:26Z                            :)
(: Purpose: Test that the typed value of element nodes is correct. :)
(:*******************************************************:)
not(data(<name>some text</name>) instance of xs:string)