(:*******************************************************:)
(: Test: K2-DirectConElemContent-12                      :)
(: Written by: Frans Englich                             :)
(: Date: 2006-08-04T17:13:26Z                            :)
(: Purpose: Test that the typed value of PI nodes is correct. :)
(:*******************************************************:)
<?target content?> instance of processing-instruction()