(:*******************************************************:)
(: Test: K-SeqUnorderedFunc-7                            :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `deep-equal((1, 2, 3), unordered((1, 2, 3)))`. :)
(:*******************************************************:)
deep-equal((1, 2, 3), unordered((1, 2, 3)))