(:*******************************************************:)
(: Test: K-SeqSubsequenceFunc-30                         :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `subsequence(error(), 1, 1)`. :)
(:*******************************************************:)
subsequence(error(), 1, 1)