(:*******************************************************:)
(: Test: K-NumericEqual-18                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:double(0) ne xs:double("NaN")`. :)
(:*******************************************************:)
xs:double(0) ne xs:double("NaN")