(:*******************************************************:)
(: Test: K-NumericEqual-11                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:integer(2) ne xs:decimal(2.6)`. :)
(:*******************************************************:)
xs:integer(2) ne xs:decimal(2.6)