(:*******************************************************:)
(: Test: K-NumericEqual-28                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:float(-1.1) eq xs:float(-1.1)`. :)
(:*******************************************************:)
xs:float(-1.1) eq xs:float(-1.1)