(:*******************************************************:)
(: Test: K-NumericEqual-5                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:integer(1) ne xs:integer(2)`. :)
(:*******************************************************:)
xs:integer(1) ne xs:integer(2)