(:*******************************************************:)
(: Test: K-NumericEqual-30                               :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:float("NaN") ne xs:float("NaN")`. :)
(:*******************************************************:)
xs:float("NaN") ne xs:float("NaN")