(:*******************************************************:)
(: Test: K-NodeNameFunc-2                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: A test whose essence is: `node-name((), "wrong param")`. :)
(:*******************************************************:)
node-name((), "wrong param")