(:*******************************************************:)
(: Test: K-TokenizeFunc-2                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: The pattern can't be the empty sequence.     :)
(:*******************************************************:)
tokenize("input", ())