(:*******************************************************:)
(: Test: K-Literals-20                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `not(xs:double("NaN"))`. :)
(:*******************************************************:)
not(xs:double("NaN"))