(:*******************************************************:)
(: Test: K-gMonthDayEQ-3                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Simple test of 'ne' for xs:gMonthDay.        :)
(:*******************************************************:)
xs:gMonthDay("--04-12") ne xs:gMonthDay("--04-11")