(:*******************************************************:)
(: Test: K-HoursFromDurationFunc-2                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `hours-from-duration((), "Wrong param")`. :)
(:*******************************************************:)
hours-from-duration((), "Wrong param")