(:*******************************************************:)
(: Test: K-GenCompEq-1                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: General comparisons involving the empty sequence. :)
(:*******************************************************:)
not(() = ())