(:*******************************************************:)
(: Test: K-GenCompEq-18                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A general comparison involving the error() function. :)
(:*******************************************************:)
3 = error()