(:*******************************************************:)
(: Test: K-SeqMINFunc-37                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `min(("a string", xs:untypedAtomic("3")))`. :)
(:*******************************************************:)
min(("a string", xs:untypedAtomic("3")))