(:*******************************************************:)
(: Test: K-SeqMINFunc-38                                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `min(QName("example.com/", "ncname"))`. :)
(:*******************************************************:)
min(QName("example.com/", "ncname"))