(:*******************************************************:)
(: Test: K-NumericLT-1                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `xs:integer(-1) lt xs:integer(1)`. :)
(:*******************************************************:)
xs:integer(-1) lt xs:integer(1)