(:*******************************************************:)
(: Test: K-ContextDefaultCollationFunc-2                 :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:41+02:00                       :)
(: Purpose: A test whose essence is: `default-collation(1, 2)`. :)
(:*******************************************************:)
default-collation(1, 2)