(:*******************************************************:)
(: Test: K-NodeLangFunc-3                                :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `if(false()) then lang("en") else true()`. :)
(:*******************************************************:)
if(false()) then lang("en") else true()