(:*******************************************************:)
(: Test: K-StringLT-2                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `not('abc' lt 'a')`. :)
(:*******************************************************:)
not('abc' lt 'a')