(:*******************************************************:)
(: Test: K-GenCompEq-40                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: General comparison where the operands are various various sequence of xs:integers. :)
(:*******************************************************:)
2 = (1, 2, 3)