(:*******************************************************:)
(: Test: K-DateAddYMD-3                                  :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: The '-' operator is not available between xs:yearMonthDuration and xs:date. :)
(:*******************************************************:)
xs:yearMonthDuration("P1Y") - xs:date("1999-08-12")