(:*******************************************************:)
(: Test: K-QuantExprWith-10                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Some-quantification carrying invalid type declarations. :)
(:*******************************************************:)
every $a as xs:anyURI in 1 satisfies count($a)