(:*******************************************************:)
(: Test: K-AdjDateToTimezoneFunc-2                       :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: A test whose essence is: `adjust-date-to-timezone((), (), "WRONG PARAM")`. :)
(:*******************************************************:)
adjust-date-to-timezone((), (), "WRONG PARAM")