(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-59                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: The fn:error() function in combination with 'instance of'. :)
(:*******************************************************:)
(error(), 1) instance of empty-sequence()