(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-48                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `1.1 instance of xs:decimal and not(1.1 instance of xs:integer)`. :)
(:*******************************************************:)
1.1 instance of xs:decimal and not(1.1 instance of xs:integer)