(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-34                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A comment appearing inside the paranteses of the sequence type element(). :)
(:*******************************************************:)
not(1 instance of element((:comment:)))