(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-41                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `(((()))) instance of empty-sequence()`. :)
(:*******************************************************:)
(((()))) instance of empty-sequence()