(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-64                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `not(((10)div(3)) instance of xs:integer)`. :)
(:*******************************************************:)
not(((10)div(3)) instance of xs:integer)