(:*******************************************************:)
(: Test: K-gMonthEQ-3                                    :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: Simple test of 'ne' for xs:gMonth.           :)
(:*******************************************************:)
xs:gMonth("--12") ne xs:gMonth("--10")