(:*******************************************************:)
(: Test: K-SeqExistsFunc-13                              :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:40+02:00                       :)
(: Purpose: fn:empty combined with fn:remove.            :)
(:*******************************************************:)
empty(remove(current-time(), 1))