(:*******************************************************:)
(: Test: K-RangeExpr-6                                   :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:36+02:00                       :)
(: Purpose: A test whose essence is: `empty(-1 to -3)`.  :)
(:*******************************************************:)
empty(-1 to -3)