(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-47                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `not("a string" instance of xs:QName)`. :)
(:*******************************************************:)
not("a string" instance of xs:QName)