(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-1                           :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `1 instance of item()`. :)
(:*******************************************************:)
1 instance of item()