(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-36                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A comment appearing inside the paranteses of the sequence type comment(). :)
(:*******************************************************:)
not(1 instance of comment((:comment:)))