(:*******************************************************:)
(: Test: K-SeqExprInstanceOf-28                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:37+02:00                       :)
(: Purpose: A test whose essence is: `not(1 instance of node())`. :)
(:*******************************************************:)
not(1 instance of node())