(:*******************************************************:)
(: Test: K-ConstructionProlog-2                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: 'declare construction Preserve' is syntactically invalid. :)
(:*******************************************************:)
(::)declare(::)construction(::)Preserve(::);(::)1(::)eq(::)1(::)