(:*******************************************************:)
(: Test: K-ConstructionProlog-3                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: Test that 'declare construction' with the strip keyword is parsed properly. :)
(:*******************************************************:)
(::)declare(::)construction(::)strip(::);(::)1(::)eq(::)1(::)