(:*******************************************************:)
(: Test: K-ConstructionProlog-1                          :)
(: Written by: Frans Englich                             :)
(: Date: 2006-10-05T18:29:39+02:00                       :)
(: Purpose: Test that 'declare construction' with the preserve keyword is parsed properly. :)
(:*******************************************************:)
(::)declare(::)construction(::)preserve(::);(::)1(::)eq(::)1(::)